[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pygame_managers"
version = "0.1.1"
description = "Collection de managers pour Pygame"
authors = [{ name = "WhiteWolf45380" }]
dependencies = ["pygame"]

[tool.setuptools.packages.find]
where = ["."]
include = ["pygame_managers*"]