[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pygame_managers"
version = "0.1.0"
description = "Collection de managers Python pour Pygame"
authors = [{ name = "WhiteWolf45380" }]
dependencies = []